version: '3'
services:
  mysql:
     image: mysql:8.0
     container_name: poc-mysql
     restart: always
     ports:
       - "3310:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=root
     volumes:
       - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
       - ./db-data:/var/lib/mysql
